import type { AppData } from '../types';

export const sampleData: AppData = {
  excerpts: [
    {
      id: 'don-juan',
      title: 'Don Juan',
      confidenceRating: 3,
      isNew: false,
      isFocus: true,
      practiceCount: 14,
      lastPracticedDate: '2026-05-19',
      dateAdded: '2026-03-05',
      notes: 'Upbow staccato at m. 9 still rushes. Keep bow distribution in the lower half.',
      tags: ['audition', 'current', 'tutti'],
      resources: [
        { id: 'r1', label: 'IMSLP', url: 'https://imslp.org' },
        { id: 'r2', label: 'Recording', url: 'https://www.youtube.com' },
      ],
      practiceHistory: [
        { id: 'h1', date: '2026-05-19', rating: 3, note: 'Tempo steadier with metronome on offbeats.' },
        { id: 'h2', date: '2026-05-16', rating: 2, note: 'Opening flourish still tense.' },
      ],
    },
    {
      id: 'scheherazade',
      title: 'Scheherazade, Mvt. II Cadenza',
      confidenceRating: 4,
      isNew: false,
      isFocus: true,
      practiceCount: 22,
      lastPracticedDate: '2026-05-20',
      dateAdded: '2026-02-18',
      notes: 'Keep vibrato continuous through the high E. Do not rush the trills.',
      tags: ['solo', 'current'],
      resources: [{ id: 'r3', label: 'YouTube', url: 'https://www.youtube.com' }],
      practiceHistory: [
        { id: 'h3', date: '2026-05-20', rating: 4, note: 'Recorded a clean take.' },
        { id: 'h4', date: '2026-05-17', rating: 4, note: '' },
      ],
    },
    {
      id: 'mendelssohn-scherzo',
      title: "Midsummer Night's Dream Scherzo",
      confidenceRating: 1,
      isNew: false,
      isFocus: false,
      practiceCount: 3,
      lastPracticedDate: '2026-05-13',
      dateAdded: '2026-04-28',
      notes: 'Spiccato is the whole battle. Start slow with a clear stroke, then build speed.',
      tags: ['audition', 'tutti'],
      resources: [],
      practiceHistory: [{ id: 'h5', date: '2026-05-13', rating: 1, note: 'Falls apart above quarter = 80.' }],
    },
    {
      id: 'brahms-4',
      title: 'Brahms Symphony No. 4, Mvt. I',
      confidenceRating: 4,
      isNew: false,
      isFocus: false,
      practiceCount: 19,
      lastPracticedDate: '2026-05-18',
      dateAdded: '2026-03-24',
      notes: 'Long-line phrasing. Sing it before playing.',
      tags: ['current', 'tutti'],
      resources: [],
      practiceHistory: [{ id: 'h6', date: '2026-05-18', rating: 4, note: 'Phrasing clicked.' }],
    },
    {
      id: 'mahler-1',
      title: 'Mahler Symphony No. 1, Mvt. III',
      confidenceRating: 5,
      isNew: false,
      isFocus: false,
      practiceCount: 31,
      lastPracticedDate: '2026-05-21',
      dateAdded: '2026-01-30',
      notes: 'Audition-ready. Maintain character without over-polishing.',
      tags: ['audition', 'solo'],
      resources: [{ id: 'r4', label: 'Recording', url: 'https://www.youtube.com' }],
      practiceHistory: [{ id: 'h7', date: '2026-05-21', rating: 5, note: 'Maintenance pass.' }],
    },
    {
      id: 'shostakovich-5',
      title: 'Shostakovich Symphony No. 5, Mvt. I',
      confidenceRating: 1,
      isNew: true,
      isFocus: false,
      practiceCount: 0,
      lastPracticedDate: null,
      dateAdded: '2026-05-21',
      notes: '',
      tags: ['new'],
      resources: [],
      practiceHistory: [],
    },
  ],
  lists: [
    { id: 'list-spring', name: 'Spring audition packet', excerptIds: ['don-juan', 'scheherazade', 'mendelssohn-scherzo'] },
    { id: 'list-maintenance', name: 'Maintenance rotation', excerptIds: ['brahms-4', 'mahler-1'] },
  ],
};
